name: isr
channels:
    - conda-forge
    - defaults
dependencies:
    - jupyterlab
    - python=3.7
    - matplotlib
    - scipy
    - tqdm
    - scikit-image
    - pillow=6.1
    - rise
